services:
  education-plataform-pg:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=docker
      - POSTGRESQL_PASSWORD=docker
      - POSTGRESQL_DATABASE=educationplataform
    volumes:
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  nginx:
    container_name: nginx
    image: nginx
    restart: always
    ports:
      - "8000:8000"
    volumes:
      - ./nginx/config:/etc/nginx/conf.d/
      - ./nginx/logs:/var/logs/nginx

  api:
    build: ./api
    ports:
      - '3000:3000'
    environment:
      - PORT=3000
      - CLIENT_URL=http://localhost:8080
      - SECREAT_KEY=123
      - DATABASE_URL=postgres://docker:docker@education-plataform-pg:5432/educationplataform
    volumes:
      - ./api:/api
    command: sh -c "cd /api && npm install && npm run dev"
    
  api-2:
    build: ./api
    ports:
      - '3008:3008'
    environment:
      - PORT=3008
      - CLIENT_URL=http://localhost:8080
      - SECREAT_KEY=123
      - DATABASE_URL=postgres://docker:docker@education-plataform-pg:5432/educationplataform
    volumes:
      - ./api:/api
    command: sh -c "cd /api && npm install && npm run dev"
    

  client:
    build: ./client
    ports:
      - '8080:8080'
    volumes:
      - ./client:/client
    command: sh -c "cd /client && npm install && npm run dev"