services:
  db:
    image: bitnami/postgresql
    ports:
      - '5434:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: educationplataform
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password
      POSTGRESQL_REPLICATION_MODE: master
      POSTGRESQL_MASTER_HOST: db
      POSTGRESQL_MASTER_PORT: 5432
      POSTGRESQL_MASTER_USER: postgres
      POSTGRESQL_MASTER_PASSWORD: 123

  db-2:
    image: bitnami/postgresql
    ports:
      - '5435:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRESQL_MASTER_HOST: db
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_PGAUDIT_LOG: READ
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password

  db-3:
    image: bitnami/postgresql
    ports:
      - '5436:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRESQL_MASTER_HOST: db
      POSTGRESQL_REPLICATION_MODE: slave
      POSTGRESQL_PGAUDIT_LOG: READ
      POSTGRESQL_REPLICATION_USER: repl_user
      POSTGRESQL_REPLICATION_PASSWORD: repl_password

  api:
    build: ./api
    ports:
      - '3000'
    environment:
      - PORT=3000
      - CLIENT_URL=http://localhost:8000
      - SECREAT_KEY=123
    volumes:
      - ./api:/api
    command: sh -c "cd /api && npm install && npm run dev"

  api-2:
    build: ./api
    ports:
      - '3000'
    environment:
      - PORT=3000
      - CLIENT_URL=http://localhost:8000
      - SECREAT_KEY=123
    volumes:
      - ./api:/api
    command: sh -c "cd /api && npm install && npm run dev"

  nginx:
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - api
    ports:
      - '8080:80'

  client:
    build: ./client
    ports:
      - '8000:8000'
    volumes:
      - ./client:/client
    command: sh -c "cd /client && npm install && npm run dev"

volumes:
  postgres-data:
