services:
  api:
    build: ./api
    ports:
      - '3000:3000'
    volumes:
      - ./api:/api

  client:
    build: ./client
    ports:
      - '8080:8080'
    volumes:
      - ./client:/client
      - /usr/src/app/node_modules
